# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0012_auto_20171205_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('asin', models.CharField(max_length=50, verbose_name='AsinId')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('brand', models.CharField(max_length=50, verbose_name='Brand')),
                ('buy_box', models.CharField(max_length=50, verbose_name='Buy Box')),
                ('price', models.CharField(max_length=10, verbose_name='Price')),
                ('total_review', models.IntegerField(default=0, verbose_name='RVW QTY')),
                ('rvw_score', models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='RVW Score')),
                ('category_rank', models.CharField(max_length=50, null=True, verbose_name='Category Rank')),
                ('inventory', models.IntegerField(default=0, verbose_name='Inventory')),
                ('is_review_watcher', models.BooleanField(default=True, verbose_name='Is Review Watcher')),
                ('is_listing_watcher', models.BooleanField(default=True, verbose_name='Is Listing Watcher')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('image_names', models.TextField(null=True, verbose_name='Images')),
                ('image_urls', models.TextField(null=True, verbose_name='Image Urls')),
            ],
            options={
                'db_table': 'product_list',
            },
        ),

        migrations.AlterField(
            model_name='userasins',
            name='is_use',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
