# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0013_auto_20171206_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='image_thumbs',
            field=models.TextField(null=True, verbose_name='Images Thumb'),
        ),

        migrations.AlterField(
            model_name='listings',
            name='category_rank',
            field=models.TextField(null=True, verbose_name='Category Rank'),
        ),
    ]
