# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0014_auto_20171208_1552'),
    ]

    operations = [

        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.CharField(max_length=10, null=True, verbose_name='Price'),
        ),
    ]
