# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0017_auto_20171212_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='date',
        ),

        migrations.AddField(
            model_name='questions',
            name='asin',
            field=models.CharField(default='', max_length=50, verbose_name='AsinId'),
        ),

        migrations.AlterField(
            model_name='userprofile',
            name='group',
            field=models.ManyToManyField(related_name='MenberGroups', to='maxlead_site.MenberGroups'),
        ),
    ]
