# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0018_auto_20171212_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50, verbose_name='Person')),
                ('answer', models.TextField(null=True, verbose_name='Answer')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
            ],
            options={
                'db_table': 'answers',
            },
        ),
        migrations.RemoveField(
            model_name='questions',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='person',
        ),

        migrations.AddField(
            model_name='questions',
            name='asked',
            field=models.CharField(default='', max_length=50, verbose_name='Asked'),
        ),

        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxlead_site.Questions'),
        ),
    ]
