# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0019_auto_20171212_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userasins',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='userasins',
            name='name',
        ),
        migrations.AddField(
            model_name='userasins',
            name='last_check',
            field=models.DateTimeField(null=True, verbose_name='Last Check'),
        ),
        migrations.AddField(
            model_name='userasins',
            name='listing_watcher',
            field=models.BooleanField(default=True, verbose_name='Listing Watcher'),
        ),
        migrations.AddField(
            model_name='userasins',
            name='review_watcher',
            field=models.BooleanField(default=True, verbose_name='Review Watcher'),
        ),
        migrations.AddField(
            model_name='userasins',
            name='sku',
            field=models.CharField(default='', max_length=50, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='person',
            field=models.CharField(max_length=225, verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='asked',
            field=models.CharField(default='', max_length=225, verbose_name='Asked'),
        ),
    ]
