# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0020_auto_20171212_1809'),
    ]

    operations = [

        migrations.AddField(
            model_name='userprofile',
            name='er_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='er_time',
            field=models.IntegerField(default=0),
        ),
    ]
