# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0021_auto_20171213_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='em_count',
            field=models.IntegerField(default=0),
        ),
    ]
