# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0022_userprofile_em_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(default=0, verbose_name='Role'),
        ),
    ]
