# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0023_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(max_length=500, verbose_name='User'),
        ),
    ]
