# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0024_auto_20171215_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.CharField(max_length=50, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(max_length=255, verbose_name='User'),
        ),
    ]
