# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0025_auto_20171215_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='image_date',
            field=models.DateField(null=True, verbose_name='Image Date'),
        ),
    ]
