# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 02:22
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0026_listings_image_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='listings',
            name='feature',
            field=models.TextField(default='', verbose_name='Feature'),
        ),
        migrations.AddField(
            model_name='menbergroups',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
