# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0027_auto_20171219_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='buy_box_res',
            field=models.CharField(default='', max_length=255, verbose_name='Buy Box Data'),
        ),
        migrations.AddField(
            model_name='userasins',
            name='buy_box',
            field=models.CharField(default='', max_length=50, verbose_name='BuyBox'),
        ),
    ]
