# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0028_auto_20171226_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='user_asin',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='maxlead_site.UserAsins'),
        ),
    ]
