# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0029_listings_user_asin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userasins',
            name='cat',
            field=models.CharField(default='', max_length=255, verbose_name='Cat1'),
        ),
        migrations.AddField(
            model_name='userasins',
            name='ownership',
            field=models.CharField(default='', max_length=50, verbose_name='Ownership'),
        ),
    ]
