# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0030_auto_20171227_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='userasins',
            name='update_time',
            field=models.DateTimeField(null=True, verbose_name='Update Time'),
        ),
    ]
