# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0031_userasins_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='image_thumbs',
            field=models.TextField(null=True, verbose_name='Images Thumb'),
        ),
    ]
