# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0032_reviews_image_thumbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='total_qa',
            field=models.IntegerField(default=0, verbose_name='qa'),
        ),
    ]
