# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 07:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maxlead_site', '0033_listings_total_qa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Name')),
                ('type', models.IntegerField(default=1, verbose_name='Type')),
                ('description', models.CharField(max_length=225, verbose_name='Description')),
                ('asins', models.CharField(max_length=225, verbose_name='Asins')),
                ('finish_time', models.DateTimeField(null=True, verbose_name='Created')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
