# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0034_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file_path',
            field=models.CharField(default='', max_length=225, verbose_name='File Path'),
        ),
    ]
