# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0035_task_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing_wacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=50, verbose_name='AsinId')),
                ('seller', models.CharField(max_length=50, verbose_name='Seller')),
                ('price', models.CharField(max_length=50, verbose_name='Price')),
                ('shipping', models.CharField(default='', max_length=255, verbose_name='Shipping')),
                ('fba', models.IntegerField(default=0, verbose_name='FBA')),
                ('prime', models.IntegerField(default=0, verbose_name='Prime')),
                ('winner', models.IntegerField(default=0, verbose_name='Winner')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
            ],
        ),
        migrations.AddField(
            model_name='listings',
            name='buy_box_link',
            field=models.CharField(default='', max_length=255, verbose_name='Buy Box Link'),
        ),
        migrations.AddField(
            model_name='listings',
            name='prime',
            field=models.IntegerField(default=0, verbose_name='Prime'),
        ),
        migrations.AddField(
            model_name='listings',
            name='shipping',
            field=models.CharField(default='', max_length=255, verbose_name='Shipping'),
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
    ]
