# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0036_auto_20180104_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing_wacher',
            new_name='ListingWacher',
        ),
        migrations.AlterModelTable(
            name='listingwacher',
            table='listing_wacher',
        ),
    ]
