# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0038_auto_20180105_1017'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='listingwacher',
            table=None,
        ),
    ]
