# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0040_auto_20180105_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingwacher',
            name='shipping',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Shipping'),
        ),
    ]
