# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0041_auto_20180105_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingwacher',
            name='price',
            field=models.CharField(max_length=50, null=True, verbose_name='Price'),
        ),
    ]
