# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0044_auto_20180105_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingwacher',
            name='images',
            field=models.CharField(default='', max_length=255, verbose_name='Images'),
        ),
    ]
