# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0045_listingwacher_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userasins',
            old_name='cat',
            new_name='cat1',
        ),
        migrations.RemoveField(
            model_name='userasins',
            name='keywords',
        ),
        migrations.AddField(
            model_name='userasins',
            name='cat2',
            field=models.CharField(default='', max_length=255, verbose_name='Cat2'),
        ),
        migrations.AddField(
            model_name='userasins',
            name='cat3',
            field=models.CharField(default='', max_length=255, verbose_name='Cat3'),
        ),
        migrations.AddField(
            model_name='userasins',
            name='keywords1',
            field=models.CharField(default='', max_length=255, verbose_name='Keywords1'),
        ),
        migrations.AddField(
            model_name='userasins',
            name='keywords2',
            field=models.CharField(default='', max_length=255, verbose_name='Keywords2'),
        ),
        migrations.AddField(
            model_name='userasins',
            name='keywords3',
            field=models.CharField(default='', max_length=255, verbose_name='Keywords3'),
        ),
    ]
