# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0046_auto_20180105_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=255, verbose_name='Asin')),
                ('cat', models.CharField(default='', max_length=255, verbose_name='Cat')),
                ('keywords', models.CharField(default='', max_length=255, verbose_name='Keywords')),
                ('rank', models.IntegerField(default=0, verbose_name='Rank')),
                ('is_ad', models.IntegerField(default=0, verbose_name='Ad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user_asin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxlead_site.UserAsins')),
            ],
        ),
        migrations.AddField(
            model_name='listings',
            name='lightning_deal',
            field=models.CharField(default='', max_length=255, verbose_name='Lightning Deal'),
        ),
        migrations.AddField(
            model_name='listings',
            name='promotion',
            field=models.TextField(default='', verbose_name='Promotion'),
        ),
    ]
