# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0047_auto_20180105_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryrank',
            name='user_asin',
            field=models.CharField(max_length=50, verbose_name='User Asin'),
        ),
    ]
