# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0048_auto_20180108_0936'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoryrank',
            table='category_rank',
        ),
    ]
