# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0051_auto_20180116_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='answered',
            field=models.CharField(default='', max_length=50, verbose_name='Answered '),
        ),
    ]
