# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0052_listings_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Count'),
        ),
    ]
