# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0053_task_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='count',
        ),
        migrations.AddField(
            model_name='questions',
            name='count',
            field=models.IntegerField(default=0, null=True, verbose_name='Count'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_new',
            field=models.IntegerField(default=0, verbose_name='New'),
        ),
    ]
