# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0055_auto_20180131_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='userasins',
            name='is_done',
            field=models.IntegerField(default=0, null=True, verbose_name='Is Done'),
        ),
    ]
