# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0056_userasins_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(null=True, verbose_name='Question'),
        ),
    ]
