# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0057_auto_20180306_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='userasins',
            name='catrank_time',
            field=models.DateTimeField(null=True, verbose_name='Catrank Time'),
        ),
        migrations.AddField(
            model_name='userasins',
            name='listing_time',
            field=models.DateTimeField(null=True, verbose_name='Listing Time'),
        ),
        migrations.AddField(
            model_name='userasins',
            name='qa_time',
            field=models.DateTimeField(null=True, verbose_name='Qa Time'),
        ),
        migrations.AddField(
            model_name='userasins',
            name='review_time',
            field=models.DateTimeField(null=True, verbose_name='Review Time'),
        ),
        migrations.AddField(
            model_name='userasins',
            name='watcher_time',
            field=models.DateTimeField(null=True, verbose_name='Watcher Time'),
        ),
    ]
