# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0058_auto_20180306_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userasins',
            name='catrank_time',
        ),
    ]
