# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0059_remove_userasins_catrank_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userasins',
            name='catrank_time',
            field=models.DateTimeField(null=True, verbose_name='Watcher Time'),
        ),
    ]
