# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-18 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0060_userasins_catrank_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsinReviewsBackcup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=50, verbose_name='AsinId')),
                ('positive_keywords', models.TextField(null=True, verbose_name='Positive Keywords')),
                ('negative_keywords', models.TextField(null=True, verbose_name='Negative Keywords')),
                ('avg_score', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Avg Score')),
                ('total_review', models.IntegerField(default=0, verbose_name='Total Reviews')),
                ('is_done', models.IntegerField(default=0, null=True, verbose_name='Done')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Create Date')),
            ],
            options={
                'db_table': 'asin_reviews_backcup',
            },
        ),
        migrations.CreateModel(
            name='ReviewsBackcup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='User')),
                ('asin', models.CharField(max_length=50, verbose_name='AsinId')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('variation', models.CharField(max_length=255, null=True, verbose_name='Variation')),
                ('content', models.TextField(default='', null=True, verbose_name='Content')),
                ('review_link', models.CharField(max_length=500, null=True, verbose_name='Review Link')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('is_vp', models.IntegerField(default=0, null=True, verbose_name='VP')),
                ('review_date', models.DateField(verbose_name='Date')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Create Date')),
                ('image_names', models.TextField(null=True, verbose_name='Images')),
                ('image_thumbs', models.TextField(null=True, verbose_name='Images Thumb')),
                ('image_urls', models.TextField(null=True, verbose_name='Image Urls')),
            ],
            options={
                'db_table': 'reviews_backcup',
            },
        ),
    ]
