# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-18 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0062_auto_20180418_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='reviewsbackcup',
            name='created',
            field=models.DateField(verbose_name='Create Date'),
        ),
    ]
