# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-18 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0064_auto_20180418_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingWacherBackcup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=50, verbose_name='AsinId')),
                ('seller', models.CharField(max_length=50, verbose_name='Seller')),
                ('seller_link', models.CharField(default='', max_length=225, null=True, verbose_name='Seller Link')),
                ('price', models.CharField(max_length=50, null=True, verbose_name='Price')),
                ('shipping', models.CharField(default='', max_length=255, null=True, verbose_name='Shipping')),
                ('fba', models.IntegerField(default=0, verbose_name='FBA')),
                ('prime', models.IntegerField(default=0, verbose_name='Prime')),
                ('winner', models.IntegerField(default=0, verbose_name='Winner')),
                ('images', models.CharField(default='', max_length=255, verbose_name='Images')),
                ('created', models.DateTimeField(verbose_name='Create Date')),
            ],
            options={
                'db_table': 'listing_wacher_backcup',
            },
        ),
    ]
