# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-18 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0065_listingwacherbackcup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingsBackcup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_asin', models.IntegerField(default=0, verbose_name='uaid')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('answered', models.CharField(default='', max_length=50, verbose_name='Answered ')),
                ('asin', models.CharField(max_length=50, verbose_name='AsinId')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('brand', models.CharField(max_length=50, verbose_name='Brand')),
                ('shipping', models.CharField(default='', max_length=255, null=True, verbose_name='Shipping')),
                ('prime', models.IntegerField(default=0, verbose_name='Prime')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('feature', models.TextField(default='', verbose_name='Feature')),
                ('promotion', models.TextField(default='', verbose_name='Promotion')),
                ('lightning_deal', models.CharField(default='', max_length=255, verbose_name='Lightning Deal')),
                ('buy_box', models.CharField(max_length=50, verbose_name='Buy Box')),
                ('buy_box_link', models.CharField(default='', max_length=255, verbose_name='Buy Box Link')),
                ('buy_box_res', models.CharField(default='', max_length=255, verbose_name='Buy Box Data')),
                ('price', models.CharField(max_length=50, null=True, verbose_name='Price')),
                ('total_review', models.IntegerField(default=0, verbose_name='RVW QTY')),
                ('total_qa', models.IntegerField(default=0, verbose_name='qa')),
                ('rvw_score', models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='RVW Score')),
                ('category_rank', models.TextField(null=True, verbose_name='Category Rank')),
                ('inventory', models.IntegerField(default=0, verbose_name='Inventory')),
                ('is_review_watcher', models.BooleanField(default=True, verbose_name='Is Review Watcher')),
                ('is_listing_watcher', models.BooleanField(default=True, verbose_name='Is Listing Watcher')),
                ('created', models.DateTimeField(verbose_name='Create Date')),
                ('image_date', models.DateField(null=True, verbose_name='Image Date')),
                ('image_names', models.TextField(null=True, verbose_name='Images')),
                ('image_thumbs', models.TextField(null=True, verbose_name='Images Thumb')),
                ('image_urls', models.TextField(null=True, verbose_name='Image Urls')),
            ],
            options={
                'db_table': 'product_list_backcup',
            },
        ),
    ]
